version = 1

test_patterns = ["**/test/**"]

exclude_patterns = [
  "static/**",
  "deploy/**",
  "contributions/**"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "cypress"
  ]